-- CompanyMarketCap mdm prod -> mdm
ALTER TABLE [mdm].[CompanyMarketCap] NOCHECK CONSTRAINT ALL;
INSERT INTO [mdm].[CompanyMarketCap] (
     [Code]
    ,[Company_Code]
    ,[CompanyID]
    ,[StockTicker_Code]
    ,[Currency_Code]
    ,[DataDate]
    ,[MarketCap]
    ,[Outcome]
    ,[Message]
    ,[TickerSymbol]
    ,[Currency]
    ,[ExchangeRate]
    ,[LastClose]
    ,[SharesOutstandingCurrent]
    ,[MarketCapCurrent]
) (
    SELECT
        [Code]
        ,[Company_Code]
        ,[CompanyID]
        ,[StockTicker_Code]
        ,[Currency_Code]
        ,[DataDate]
        ,[MarketCap]
        ,[Outcome]
        ,[Message]
        ,[TickerSymbol]
        ,[Currency]
        ,[ExchangeRate]
        ,[LastClose]
        ,[SharesOutstandingCurrent]
        ,[MarketCapCurrent]
    FROM [172.16.16.5,29999].[BCIQ_ODS].[mdm].[CompanyMarketCap]
    WHERE DataDate > '2021-12-31'
);

ALTER TABLE [mdm].[CompanyMarketCap] CHECK CONSTRAINT ALL;

-- CompanyMarketCap mdm test -> ods test
ALTER TABLE [ods].[CompanyMarketCap] NOCHECK CONSTRAINT ALL;
INSERT INTO [ods].[CompanyMarketCap] (
     [Code]
    ,[Company_Code]
    ,[CompanyID]
    ,[StockTicker_Code]
    ,[Currency_Code]
    ,[DataDate]
    ,[MarketCap]
    ,[Outcome]
    ,[Message]
    ,[TickerSymbol]
    ,[Currency]
    ,[ExchangeRate]
    ,[LastClose]
    ,[SharesOutstandingCurrent]
    ,[MarketCapCurrent]
) (
    SELECT
        [Code]
        ,[Company_Code]
        ,[CompanyID]
        ,[StockTicker_Code]
        ,[Currency_Code]
        ,[DataDate]
        ,[MarketCap]
        ,[Outcome]
        ,[Message]
        ,[TickerSymbol]
        ,[Currency]
        ,[ExchangeRate]
        ,[LastClose]
        ,[SharesOutstandingCurrent]
        ,[MarketCapCurrent]
    FROM [mdm].[CompanyMarketCap]
);

ALTER TABLE [ods].[CompanyMarketCap] CHECK CONSTRAINT ALL;

-- DealDocuments mdm prod -> mdm test
SET IDENTITY_INSERT [mdm].[DealDocuments] ON;
ALTER TABLE [mdm].[DealDocuments] NOCHECK CONSTRAINT ALL;
INSERT INTO [mdm].[DealDocuments] (
		[Code]
      ,[Name]
      ,[Deal_Code]
      ,[Deal_Name]
      ,[DealID]
      ,[DocumentID]
      ,[DocumentType_Code]
      ,[DocumentType_Name]
      ,[DealEventCode]
      ,[FileName]
      ,[DocumentDate]
      ,[DocumentSource]
      ,[Notes]
      ,[CreatedUser]
      ,[CreatedDateTime]
      ,[UpdatedUser]
      ,[UpdatedDateTime]
      ,[FileURL]
) (
    SELECT
		[Code]
      ,[Name]
      ,[Deal_Code]
      ,[Deal_Name]
      ,[DealID]
      ,[DocumentID]
      ,[DocumentType_Code]
      ,[DocumentType_Name]
      ,[DealEventCode]
      ,[FileName]
      ,[DocumentDate]
      ,[DocumentSource]
      ,[Notes]
      ,[CreatedUser]
      ,[CreatedDateTime]
      ,[UpdatedUser]
      ,[UpdatedDateTime]
      ,[FileURL]
    FROM [172.16.16.5,29999].[BCIQ_ODS].[mdm].[DealDocuments]
    WHERE [CreatedDateTime] > '2021-12-31'
);

ALTER TABLE [mdm].[DealDocuments] CHECK CONSTRAINT ALL;
SET IDENTITY_INSERT [mdm].[DealDocuments] OFF;

-- DealDocuments mdm test -> ods test
SET IDENTITY_INSERT [ods].[DealDocuments] ON;
ALTER TABLE [ods].[DealDocuments] NOCHECK CONSTRAINT ALL;
INSERT INTO [ods].[DealDocuments] (
		[Code]
      ,[Name]
      ,[Deal_Code]
      ,[Deal_Name]
      ,[DealID]
      ,[DocumentID]
      ,[DocumentType_Code]
      ,[DocumentType_Name]
      ,[DealEventCode]
      ,[FileName]
      ,[DocumentDate]
      ,[DocumentSource]
      ,[Notes]
      ,[CreatedUser]
      ,[CreatedDateTime]
      ,[UpdatedUser]
      ,[UpdatedDateTime]
      ,[FileURL]
) (
    SELECT
		[Code]
      ,[Name]
      ,[Deal_Code]
      ,[Deal_Name]
      ,[DealID]
      ,[DocumentID]
      ,[DocumentType_Code]
      ,[DocumentType_Name]
      ,[DealEventCode]
      ,[FileName]
      ,[DocumentDate]
      ,[DocumentSource]
      ,[Notes]
      ,[CreatedUser]
      ,[CreatedDateTime]
      ,[UpdatedUser]
      ,[UpdatedDateTime]
      ,[FileURL]
    FROM [BCIQ_ODS].[mdm].[DealDocuments]
);

ALTER TABLE [ods].[DealDocuments] CHECK CONSTRAINT ALL;
SET IDENTITY_INSERT [ods].[DealDocuments] OFF;

-- Stocks mdm prod -> mdm test
SET IDENTITY_INSERT [mdm].[Stocks] ON;
ALTER TABLE [mdm].[Stocks] NOCHECK CONSTRAINT ALL;
INSERT INTO [mdm].[Stocks] (
      [Code]
      ,[Company_Code]
      ,[CompanyID]
      ,[StockTicker_Code]
      ,[TickerSymbol]
      ,[MarketCode]
      ,[TradeDate]
      ,[LastSharePrice]
      ,[OpenSharePrice]
      ,[HighSharePrice]
      ,[LowSharePrice]
      ,[Volume]
      ,[LastClose]
      ,[ChangeFromOpen]
      ,[PercentChangeFromOpen]
      ,[ChangeFromLastClose]
      ,[PercentChangeFromLastClose]
      ,[SplitRatio]
      ,[CumulativeCashDividend]
      ,[CummulativeStockDividend]
      ,[CumulativeStockDividendRatio]
      ,[Currency]
      ,[AdjustmentMethodUsed]
      ,[DataConfidence]
      ,[LastPriceSource]
      ,[LastPriceType]
      ,[EndOfDayPrice]
      ,[EndOfDayPriceDate]
      ,[EndOfDayPriceMethodUsed]
      ,[EndOfDayPriceTiming]
      ,[EndOfDayPriceSource]
      ,[ExchangeClose]
      ,[Valuation]
      ,[ExchangeCloseDate]
      ,[ValuationDate]
      ,[Outcome]
      ,[Message]
      ,[RequestDate]
      ,[IsProcessed]
      ,[OriginalClosePrice]
      ,[OriginalVolume]
      ,[ExchangeRate]
      ,[IsPrimaryCode]
      ,[UpdatedUser]
      ,[UpdatedDateTime]
) (
    SELECT
      [Code]
      ,[Company_Code]
      ,[CompanyID]
      ,[StockTicker_Code]
      ,[TickerSymbol]
      ,[MarketCode]
      ,[TradeDate]
      ,[LastSharePrice]
      ,[OpenSharePrice]
      ,[HighSharePrice]
      ,[LowSharePrice]
      ,[Volume]
      ,[LastClose]
      ,[ChangeFromOpen]
      ,[PercentChangeFromOpen]
      ,[ChangeFromLastClose]
      ,[PercentChangeFromLastClose]
      ,[SplitRatio]
      ,[CumulativeCashDividend]
      ,[CummulativeStockDividend]
      ,[CumulativeStockDividendRatio]
      ,[Currency]
      ,[AdjustmentMethodUsed]
      ,[DataConfidence]
      ,[LastPriceSource]
      ,[LastPriceType]
      ,[EndOfDayPrice]
      ,[EndOfDayPriceDate]
      ,[EndOfDayPriceMethodUsed]
      ,[EndOfDayPriceTiming]
      ,[EndOfDayPriceSource]
      ,[ExchangeClose]
      ,[Valuation]
      ,[ExchangeCloseDate]
      ,[ValuationDate]
      ,[Outcome]
      ,[Message]
      ,[RequestDate]
      ,[IsProcessed]
      ,[OriginalClosePrice]
      ,[OriginalVolume]
      ,[ExchangeRate]
      ,[IsPrimaryCode]
      ,[UpdatedUser]
      ,[UpdatedDateTime]
    FROM [172.16.16.5,29999].[BCIQ_ODS].[mdm].[Stocks]
    WHERE [TradeDate] > '2021-12-31'
);

ALTER TABLE [mdm].[Stocks] CHECK CONSTRAINT ALL;
SET IDENTITY_INSERT [mdm].[Stocks] OFF;

-- Stocks mdm test -> ods test
SET IDENTITY_INSERT [ods].[Stocks] ON;
ALTER TABLE [ods].[Stocks] NOCHECK CONSTRAINT ALL;
INSERT INTO [ods].[Stocks] (
      [Code]
      ,[Company_Code]
      ,[CompanyID]
      ,[StockTicker_Code]
      ,[TickerSymbol]
      ,[MarketCode]
      ,[TradeDate]
      ,[LastSharePrice]
      ,[OpenSharePrice]
      ,[HighSharePrice]
      ,[LowSharePrice]
      ,[Volume]
      ,[LastClose]
      ,[ChangeFromOpen]
      ,[PercentChangeFromOpen]
      ,[ChangeFromLastClose]
      ,[PercentChangeFromLastClose]
      ,[SplitRatio]
      ,[CumulativeCashDividend]
      ,[CummulativeStockDividend]
      ,[CumulativeStockDividendRatio]
      ,[Currency]
      ,[AdjustmentMethodUsed]
      ,[DataConfidence]
      ,[LastPriceSource]
      ,[LastPriceType]
      ,[EndOfDayPrice]
      ,[EndOfDayPriceDate]
      ,[EndOfDayPriceMethodUsed]
      ,[EndOfDayPriceTiming]
      ,[EndOfDayPriceSource]
      ,[ExchangeClose]
      ,[Valuation]
      ,[ExchangeCloseDate]
      ,[ValuationDate]
      ,[Outcome]
      ,[Message]
      ,[RequestDate]
      ,[IsProcessed]
      ,[OriginalClosePrice]
      ,[OriginalVolume]
      ,[ExchangeRate]
      ,[IsPrimaryCode]
      ,[UpdatedUser]
      ,[UpdatedDateTime]
) (
    SELECT
      [Code]
      ,[Company_Code]
      ,[CompanyID]
      ,[StockTicker_Code]
      ,[TickerSymbol]
      ,[MarketCode]
      ,[TradeDate]
      ,[LastSharePrice]
      ,[OpenSharePrice]
      ,[HighSharePrice]
      ,[LowSharePrice]
      ,[Volume]
      ,[LastClose]
      ,[ChangeFromOpen]
      ,[PercentChangeFromOpen]
      ,[ChangeFromLastClose]
      ,[PercentChangeFromLastClose]
      ,[SplitRatio]
      ,[CumulativeCashDividend]
      ,[CummulativeStockDividend]
      ,[CumulativeStockDividendRatio]
      ,[Currency]
      ,[AdjustmentMethodUsed]
      ,[DataConfidence]
      ,[LastPriceSource]
      ,[LastPriceType]
      ,[EndOfDayPrice]
      ,[EndOfDayPriceDate]
      ,[EndOfDayPriceMethodUsed]
      ,[EndOfDayPriceTiming]
      ,[EndOfDayPriceSource]
      ,[ExchangeClose]
      ,[Valuation]
      ,[ExchangeCloseDate]
      ,[ValuationDate]
      ,[Outcome]
      ,[Message]
      ,[RequestDate]
      ,[IsProcessed]
      ,[OriginalClosePrice]
      ,[OriginalVolume]
      ,[ExchangeRate]
      ,[IsPrimaryCode]
      ,[UpdatedUser]
      ,[UpdatedDateTime]
    FROM [BCIQ_ODS].[mdm].[Stocks]
);

ALTER TABLE [ods].[Stocks] CHECK CONSTRAINT ALL;
SET IDENTITY_INSERT [ods].[Stocks] OFF;

