DELETE FROM [BCIQ_DW].[app].[Letter]
DELETE FROM [BCIQ_DW].[app].[UserTable]
DELETE FROM [BCIQ_DW].[app].[Alert]
DELETE FROM [BCIQ_DW].[app].[User]
DELETE FROM [BCIQ_DW].[app].[AlertCard]
DELETE FROM [BCIQ_DW].[app].[ApplicationSetting]
DELETE FROM [BCIQ_DW].[app].[FullEdition]
DELETE FROM [BCIQ_DW].[app].[Cache]

SELECT * FROM [BCIQ_DW].[app].[Letter]
SELECT * FROM [BCIQ_DW].[app].[UserTable]
SELECT * FROM [BCIQ_DW].[app].[Alert]
SELECT * FROM [BCIQ_DW].[app].[User]
SELECT * FROM [BCIQ_DW].[app].[AlertCard]
SELECT * FROM [BCIQ_DW].[app].[ApplicationSetting]
SELECT * FROM [BCIQ_DW].[app].[FullEdition]
SELECT * FROM [BCIQ_DW].[app].[Cache]
