SELECT * FROM [BCIQ_DW].[app].[Letters]
SELECT * FROM [BCIQ_DW].[app].[UserTables]
SELECT * FROM [BCIQ_DW].[app].[Alerts]
SELECT * FROM [BCIQ_DW].[app].[Users]
SELECT * FROM [BCIQ_DW].[app].[AlertCards]
SELECT * FROM [BCIQ_DW].[app].[ApplicationSettings]
SELECT * FROM [BCIQ_DW].[app].[FullEditions]
SELECT * FROM [BCIQ_DW].[app].[Cache]