DECLARE @Search VARCHAR(50);

SET @Search = '%MolecularTarget%';

--SELECT DISTINCT TABLE_NAME, TABLE_SCHEMA
--FROM BCIQ_ODS.INFORMATION_SCHEMA.TABLES 
--WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA IN ('mdm', 'ods', 'dbo') AND TABLE_NAME LIKE @Search
--ORDER BY TABLE_NAME

SELECT DISTINCT a.TABLE_NAME, a.COLUMN_NAME, a.TABLE_SCHEMA
    FROM BCIQ_ODS.INFORMATION_SCHEMA.COLUMNS AS a
    WHERE a.TABLE_SCHEMA IN ('mdm', 'ods', 'dbo') AND a.COLUMN_NAME LIKE @Search