-- get scripts for NOCHECK 
SELECT 'ALTER TABLE [ods].[' + TABLE_NAME + '] NOCHECK CONSTRAINT ALL;'
FROM BCIQ_ODS.INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = 'ods'
ORDER BY TABLE_NAME

SELECT 'ALTER TABLE [mdm].[' + TABLE_NAME + '] NOCHECK CONSTRAINT ALL;'
FROM BCIQ_ODS.INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = 'mdm'
ORDER BY TABLE_NAME

-- get scripts for CHECK 
SELECT 'ALTER TABLE [ods].[' + TABLE_NAME + '] CHECK CONSTRAINT ALL;'
FROM BCIQ_ODS.INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = 'ods'
ORDER BY TABLE_NAME

SELECT 'ALTER TABLE [mdm].[' + TABLE_NAME + '] CHECK CONSTRAINT ALL;'
FROM BCIQ_ODS.INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = 'mdm'
ORDER BY TABLE_NAME