DECLARE @Table TABLE (ID INT IDENTITY(1,1),TABLE_NAME VARCHAR(50),COLUMN_NAME VARCHAR(50))
DECLARE c CURSOR READ_ONLY FAST_FORWARD FOR SELECT a.TABLE_NAME FROM BCIQ_ODS.INFORMATION_SCHEMA.TABLES AS a WHERE a.TABLE_SCHEMA = 'mdm' AND a.TABLE_TYPE = 'BASE TABLE'
DECLARE @tableName VARCHAR(50);

OPEN c

FETCH NEXT FROM c INTO @tableName
WHILE (@@FETCH_STATUS = 0)
BEGIN
    INSERT INTO @Table
    SELECT a.TABLE_NAME, a.COLUMN_NAME
    FROM BCIQ_ODS.INFORMATION_SCHEMA.COLUMNS AS a
    WHERE a.TABLE_SCHEMA = 'ods' AND a.TABLE_NAME = @tableName
    EXCEPT
    SELECT b.TABLE_NAME, b.COLUMN_NAME 
    FROM BCIQ_ODS.INFORMATION_SCHEMA.COLUMNS AS b
    WHERE b.TABLE_SCHEMA = 'mdm' AND b.TABLE_NAME = @tableName

    FETCH NEXT FROM c INTO @tableName
END

CLOSE c
DEALLOCATE c

SELECT * FROM @Table