-- Deal_to_Company
ALTER TABLE [ods].[Deal_to_Company] NOCHECK CONSTRAINT ALL;

INSERT INTO [BCIQ_ODS].[ods].[Deal_to_Company] (
       [Name]
      ,[Deal_Code]
      ,[Deal_Name]
      ,[Company_Code]
      ,[Company_Name]
      ,[CompanyRole_Code]
      ,[CompanyRole_Name]
      ,[CompanyRank]
      ,[CompanyHQCountryID]
      ,[CompanyTypeID]
      ,[Responsibilities]
      ,[DatePrior]
      ,[StockPricePrior]
      ,[StockPricePriorUSD]
      ,[StockValue]
      ,[CashValue]
      ,[SwapRate]
      ,[SharesIssued]
      ,[SharesOutstanding]
      ,[SharesOutstandingDate]
      ,[MarketValue]
      ,[MarketValueDate]
      ,[ExchangeRate]
      ,[CurrencyID]
      ,[OwnershipID]
      ,[ExchangeID1]
      ,[ExchangeID2]
      ,[Ticker1]
      ,[Ticker2]
      ,[PctOwnership]
      ,[CreatedUser]
      ,[UpdatedUser]
      ,[CreatedDateTime]
      ,[UpdatedDateTime]
) (
	SELECT 
      dtc.[Name]
      ,dt.[odsCode] as Deal_Code
      ,dtc.[Deal_Name]
      ,dtc.[Company_Code]
      ,dtc.[Company_Name]
      ,dtc.[CompanyRole_Code]
      ,dtc.[CompanyRole_Name]
      ,dtc.[CompanyRank]
      ,dtc.[CompanyHQCountryID]
      ,dtc.[CompanyTypeID]
      ,dtc.[Responsibilities]
      ,dtc.[DatePrior]
      ,dtc.[StockPricePrior]
      ,dtc.[StockPricePriorUSD]
      ,dtc.[StockValue]
      ,dtc.[CashValue]
      ,dtc.[SwapRate]
      ,dtc.[SharesIssued]
      ,dtc.[SharesOutstanding]
      ,dtc.[SharesOutstandingDate]
      ,dtc.[MarketValue]
      ,dtc.[MarketValueDate]
      ,dtc.[ExchangeRate]
      ,dtc.[CurrencyID]
      ,dtc.[OwnershipID]
      ,dtc.[ExchangeID1]
      ,dtc.[ExchangeID2]
      ,dtc.[Ticker1]
      ,dtc.[Ticker2]
      ,dtc.[PctOwnership]
      ,dtc.[CreatedUser]
      ,dtc.[UpdatedUser]
      ,dtc.[CreatedDateTime]
      ,dtc.[UpdatedDateTime]
	  FROM [BCIQ_ODS].[api].[Deal_to_Company] dtc
	  JOIN [BCIQ_ODS].[ods].[Deals_Temp] dt ON dt.ApiCode = dtc.Deal_Code
	  WHERE dt.Code != 9999
);

ALTER TABLE [ods].[Deal_to_Company] CHECK CONSTRAINT ALL;