DELETE FROM [BCIQ_DW].[app].[Alert]
DELETE FROM [BCIQ_DW].[app].[AlertCard]
DELETE FROM [BCIQ_DW].[app].[ApplicationSetting]
DELETE FROM [BCIQ_DW].[app].[Cache]
DELETE FROM [BCIQ_DW].[app].[FullEdition]
DELETE FROM [BCIQ_DW].[app].[Letter]
DELETE FROM [BCIQ_DW].[app].[User]
DELETE FROM [BCIQ_DW].[app].[UserTable]
DELETE FROM [BCIQ_DW].[app].[Report]

SELECT * FROM [BCIQ_DW].[app].[Alert]
SELECT * FROM [BCIQ_DW].[app].[AlertCard]
SELECT * FROM [BCIQ_DW].[app].[ApplicationSetting]
SELECT * FROM [BCIQ_DW].[app].[Cache]
SELECT * FROM [BCIQ_DW].[app].[FullEdition]
SELECT * FROM [BCIQ_DW].[app].[Letter]
SELECT * FROM [BCIQ_DW].[app].[User]
SELECT * FROM [BCIQ_DW].[app].[UserTable]
SELECT * FROM [BCIQ_DW].[app].[Report]

SELECT Count(*) AS [Alert] FROM [BCIQ_DW].[app].[Alert]
SELECT Count(*) AS [AlertCard] FROM [BCIQ_DW].[app].[AlertCard]
SELECT Count(*) AS [ApplicationSetting] FROM [BCIQ_DW].[app].[ApplicationSetting]
SELECT Count(*) AS [Cache] FROM [BCIQ_DW].[app].[Cache]
SELECT Count(*) AS [FullEdition] FROM [BCIQ_DW].[app].[FullEdition]
SELECT Count(*) AS [Letter] FROM [BCIQ_DW].[app].[Letter]
SELECT Count(*) AS [User] FROM [BCIQ_DW].[app].[User]
SELECT Count(*) AS [UserTable] FROM [BCIQ_DW].[app].[UserTable]
SELECT Count(*) AS [Report] FROM [BCIQ_DW].[app].[Report]
